name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  linuxbrew:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: Homebrew/actions/setup-homebrew@8f3d1ec8a696b3b9d9a6c3696b6c73033cab69e4 # main 2026-08-16
      - name: Install and test formula
        run: |
          brew install --formula ./Formula/rootbroker.rb
          rootbroker version
          rootbroker-setup --help
          brew test rootbroker
          test ! -e /var/lib/rootbroker/install-state
